language: rust

rust:
  - stable

addons:
  apt:
    packages:
      - gcc-arm-none-eabi

install:
  - rustup target add thumbv7m-none-eabi

script:
  - cargo build --verbose
  - cargo build --verbose --examples
